name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: default  # Ensure this matches the environment name in your yml file
        environment-file: .ci_support/environment.yml
        python-version: 3.11  # Ensure this matches the python version you need

    - name: Run tests
      run: |
        conda activate default
        python -m unittest discover -s tests -p "test_paradis.py"

